[versions]
agp = "8.1.4"
kotlin = "1.9.20"
secrets = "2.0.1"
ksp = "1.9.20-1.0.14"
hilt = "2.48.1"
gms = "4.3.14"
firebasecrashlyticsplugin = "2.9.9"

#Android Compose  Dep Version
composeActivity = "1.8.1"
composeBom = "2023.10.01"
composeCompiler = "1.5.4"
composeNavigation = "2.7.5"
composeFoundation = "1.5.1"
accompanist = "0.30.1"
constraintlayoutCompose = "1.0.1"
composeHiltNavigation = "1.1.0"

#Android MDC Core Dep Version
androidxAppcompat = "1.6.1"
androidxCoreKtx = "1.12.0"
material = "1.10.0"
recyclerview = "1.3.2"
activity = "1.8.1"
fragment = "1.6.2"
constraintLayout = "2.1.4"
cardview = "1.0.0"
browser ="1.7.0"
swiperefreshlayout = "1.1.0"
navigationComponent = "2.7.5"
navigationComponentHilt = "1.1.0"
lifecycle = "2.6.2"
preference = "1.2.1"

retrofit2 = "2.9.0"
okhHttp3 = "4.12.0"
gson = "2.10.1"
rxjava3 = "3.1.7"
rxjava3Android = "3.0.2"
lottie = "6.1.0"
timber = "5.0.1"
dateced = "1.1.1"
alerter = "7.2.4"
photoview = "2.3.0"
circleimage = "3.1.0"
coil = "2.5.0"
dotsindicator = "4.3"
appupdate = "2.1.0"
facebook = "latest.release"
maps = "18.2.0"
mapsLocation = "21.0.1"
mapsPlaces = "3.3.0"
firebase = "32.6.0"
room = "2.6.0"
playstorereview = "2.0.1"
desugar = "2.0.4"
kotlinxCoroutines = "1.7.3"
viewstate = "1.1.1"
customview = "1.1.1"
customTabs ="3.0.3"
sdp = "1.1.0"
junit = "4.13.2"
extjunit = "1.1.5"
espresso = "3.5.1"
org-jetbrains-kotlin-android = "1.9.0"

[bundles]
network = ["retrofit2.core","retrofit2.rx3adapter","retrofit2.gsonconverter","gson","okhHttp3.core","okhHttp3.interceptor","kotlinx-coroutines-android"]
rxJava3 = ["rxjava3.core","rxjava3.android"]

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-iconsExtended= { group = "androidx.compose.material", name = "material-icons-extended"}
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation"}
androidx-compose-activity = {group = "androidx.activity", name="activity-compose", version.ref="composeActivity"}
androidx-compose-navigation = {group = "androidx.navigation", name="navigation-compose", version.ref="composeNavigation"}
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-compose-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "composeHiltNavigation" }

androidx-appcompat = {group = "androidx.appcompat", name = "appcompat", version.ref="androidxAppcompat"}
androidx-corektx = {group = "androidx.core", name = "core-ktx", version.ref="androidxCoreKtx"}
androidx-constraintlayout = {group = "androidx.constraintlayout", name = "constraintlayout", version.ref="constraintLayout"}
androidx-material = {group = "com.google.android.material", name = "material", version.ref="material"}
androidx-fragment = {group = "androidx.fragment", name = "fragment-ktx", version.ref="fragment"}
androidx-activity = {group = "androidx.activity", name = "activity-ktx", version.ref="activity"}
androidx-cardview = {group = "androidx.cardview", name = "cardview", version.ref="cardview"}
androidx-browser = {group = "androidx.browser", name = "browser", version.ref="browser"}
androidx-recyclerview = {group = "androidx.recyclerview", name = "recyclerview", version.ref="recyclerview"}
androidx-preference = {group = "androidx.preference", name = "preference", version.ref="preference"}
androidx-swiperefreshlayout = {group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref="swiperefreshlayout"}

androidx-lifecycle-viewmodel-ktx = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref="lifecycle"}
androidx-lifecycle-viewmodel-savedstate = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref="lifecycle"}
androidx-lifecycle-livedata = {group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref="lifecycle"}
androidx-lifecycle-runtime = {group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref="lifecycle"}
androidx-lifecycle-commonjava8 = {group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref="lifecycle"}
androidx-lifecycle-service = {group = "androidx.lifecycle", name = "lifecycle-service", version.ref="lifecycle"}
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

androidx-navigation-ktx = {group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref="navigationComponent"}
androidx-navigation-ui = {group = "androidx.navigation", name = "navigation-ui-ktx", version.ref="navigationComponent"}

hilt-android = {group = "com.google.dagger", name = "hilt-android", version.ref="hilt"}
hilt-compiler = {group = "com.google.dagger", name = "hilt-android-compiler", version.ref="hilt"}

retrofit2-core = {group = "com.squareup.retrofit2", name = "retrofit", version.ref="retrofit2"}
retrofit2-rx3adapter = {group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref="retrofit2"}
retrofit2-gsonconverter = {group = "com.squareup.retrofit2", name = "converter-gson", version.ref="retrofit2"}
gson = {group = "com.google.code.gson", name = "gson", version.ref="gson"}
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

alerter-tapadoo = { group = "com.github.tapadoo", name = "alerter", version.ref = "alerter"}

okhHttp3-core = {group = "com.squareup.okhttp3", name = "okhttp", version.ref="okhHttp3"}
okhHttp3-interceptor = {group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref="okhHttp3"}

rxjava3-core = {group = "io.reactivex.rxjava3", name = "rxjava", version.ref="rxjava3"}
rxjava3-android = {group = "io.reactivex.rxjava3", name = "rxandroid", version.ref="rxjava3Android"}

image-photoviewzoom = {group = "com.github.chrisbanes", name = "PhotoView", version.ref="photoview"}
image-circleimage = {group = "de.hdodenhof", name = "circleimageview", version.ref="circleimage"}
image-coil-compose = {group = "io.coil-kt", name = "coil-compose", version.ref="coil"}
image-coil = {group = "io.coil-kt", name = "coil", version.ref="coil"}
indicator-dot =  {group = "com.tbuonomo", name = "dotsindicator", version.ref="dotsindicator"}

log-timber = {group = "com.jakewharton.timber", name = "timber", version.ref="timber"}
animation-lottie = {group = "com.airbnb.android", name = "lottie", version.ref="lottie"}
dimension-sdp = {group = "com.intuit.sdp", name = "sdp-android", version.ref="sdp"}
dimension-ssp = {group = "com.intuit.ssp", name = "ssp-android", version.ref="sdp"}

kamrul3288-viewstate = {group = "com.github.kamrul3288", name = "viewstatelayout", version.ref="viewstate"}
kamrul3288-customview = {group = "com.github.kamrul3288", name = "customview-android", version.ref="customview"}
kamrul3288-dateced = {group = "com.github.kamrul3288", name = "dateced", version.ref="dateced"}

appupdate-core = {group = "com.google.android.play", name = "app-update", version.ref="appupdate"}
appupdate-ktx = {group = "com.google.android.play", name = "app-update-ktx", version.ref="appupdate"}

review-core = {group = "com.google.android.play", name = "review", version.ref="playstorereview"}
review-ktx = {group = "com.google.android.play", name = "review-ktx", version.ref="playstorereview"}

room-ktx = {group = "androidx.room", name = "room-ktx", version.ref="room"}
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref="room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref="room"}
room-common = {group = "androidx.room", name = "room-common", version.ref="room"}

firebase-bom = {group = "com.google.firebase", name = "firebase-bom", version.ref="firebase"}
firebase-messaging = {group = "com.google.firebase", name = "firebase-messaging-ktx"}
firebase-analytics = {group = "com.google.firebase", name = "firebase-analytics-ktx"}
firebase-crashlytics = {group = "com.google.firebase", name = "firebase-crashlytics-ktx"}

maps-sdk = {group = "com.google.android.gms", name = "play-services-maps", version.ref="maps"}
maps-location = {group = "com.google.android.gms", name = "play-services-location", version.ref="mapsLocation"}
maps-places = {group = "com.google.android.libraries.places", name = "places", version.ref="mapsPlaces"}

facebook-sdk = {group = "com.facebook.android", name = "facebook-android-sdk", version.ref="facebook"}
facebook-marketing = {group = "com.facebook.android", name = "facebook-marketing", version.ref="facebook"}

customtabs = {group = "de.peilicke.sascha", name = "android-customtabs", version.ref="customTabs"}
test-junit = {group = "junit", name = "junit", version.ref="junit"}
test-extjunit = {group = "androidx.test.ext", name = "junit", version.ref="extjunit"}
test-espresso = {group = "androidx.test.espresso", name = "espresso-core", version.ref="espresso"}
test-compose-ui-junit = { group = "androidx.compose.ui", name = "ui-test-junit4"}

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebasecrashlyticsplugin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
com-google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebasecrashlyticsplugin" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "gms" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigationComponent" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

# Plugins defined by this project
iamkamrul-android-application = { id = "iamkamrul.android.application", version = "unspecified" }
iamkamrul-android-application-compose = { id = "iamkamrul.android.application.compose", version = "unspecified" }
iamkamrul-android-application-firebase = { id = "iamkamrul.android.application.firebase", version = "unspecified" }
iamkamrul-android-hilt = { id = "iamkamrul.android.hilt", version = "unspecified" }
iamkamrul-android-library = { id = "iamkamrul.android.library", version = "unspecified" }
iamkamrul-android-library-compose = { id = "iamkamrul.android.library.compose", version = "unspecified" }
iamkamrul-android-feature-compose = { id = "iamkamrul.android.feature.compose", version = "unspecified" }
iamkamrul-android-room = { id = "iamkamrul.android.room", version = "unspecified" }
iamkamrul-android-retrofit = { id = "iamkamrul.android.retrofit", version = "unspecified" }
iamkamrul-jvm-library = { id = "iamkamrul.jvm.library", version = "unspecified" }